In [5]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
from sklearn.tree import DecisionTreeRegressor

In [6]:
# save filepath to variable for easier access
home_data_file_path = 'train.csv'

# read the data and store data in DataFrame titled home_data
home_data = pd.read_csv(home_data_file_path) 

# print a summary of the data in Melbourne data
home_data.describe()

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SalePrice
count,1460.000000,1460.000000,1201.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1452.000000,1460.000000,...,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000
mean,730.500000,56.897260,70.049958,10516.828082,6.099315,5.575342,1971.267808,1984.865753,103.685262,443.639726,...,94.244521,46.660274,21.954110,3.409589,15.060959,2.758904,43.489041,6.321918,2007.815753,180921.195890
std,421.610009,42.300571,24.284752,9981.264932,1.382997,1.112799,30.202904,20.645407,181.066207,456.098091,...,125.338794,66.256028,61.119149,29.317331,55.757415,40.177307,496.123024,2.703626,1.328095,79442.502883
min,1.000000,20.000000,21.000000,1300.000000,1.000000,1.000000,1872.000000,1950.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,2006.000000,34900.000000
25%,365.750000,20.000000,59.000000,7553.500000,5.000000,5.000000,1954.000000,1967.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.000000,2007.000000,129975.000000
50%,730.500000,50.000000,69.000000,9478.500000,6.000000,5.000000,1973.000000,1994.000000,0.000000,383.500000,...,0.000000,25.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.000000,2008.000000,163000.000000
75%,1095.250000,70.000000,80.000000,11601.500000,7.000000,6.000000,2000.000000,2004.000000,166.000000,712.250000,...,168.000000,68.000000,0.000000,0.000000,0.000000,0.000000,0.000000,8.000000,2009.000000,214000.000000
max,1460.000000,190.000000,313.000000,215245.000000,10.000000,9.000000,2010.000000,2010.000000,1600.000000,5644.000000,...,857.000000,547.000000,552.000000,508.000000,480.000000,738.000000,15500.000000,12.000000,2010.000000,755000.000000

In [7]:
# printing all columns
home_data.columns

Index(['Id', 'MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street',
       'Alley', 'LotShape', 'LandContour', 'Utilities', 'LotConfig',
       'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType',
       'HouseStyle', 'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd',
       'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType',
       'MasVnrArea', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual',
       'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1',
       'BsmtFinType2', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating',
       'HeatingQC', 'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF',
       'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath',
       'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual',
       'TotRmsAbvGrd', 'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType',
       'GarageYrBlt', 'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual',
       'GarageCond', 'PavedDrive', 'WoodDeckSF', 'OpenPorchSF',
       'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'PoolArea', 'PoolQC',
       'Fence', 'MiscFeature', 'MiscVal', 'MoSold', 'YrSold', 'SaleType',
       'SaleCondition', 'SalePrice'],
      dtype='object')

In [8]:
# ask for features the user wants considered
features = input('Enter features to be considered separated by a comma: ')
ft_list = []
features = features.replace(' ','')
features = features.replace("'","")

# converting input to a list and confirming that each feature is valid
for feature in features.split(','):
    if feature in home_data.columns:
        ft_list.append(feature)
        
# 'Fence', 'MiscFeature', 'MiscVal', 'MoSold', 'YrSold', 'SaleType',        'SaleCondition'
print(ft_list)

train_X = home_data[ft_list] # list of features from our training set train.csv
train_X = pd.get_dummies(train_X)
train_y = home_data.SalePrice # corresponding Sale Price

test_path = 'test.csv'
test_data = pd.read_csv(test_path) 
test_X = test_data[ft_list] # list of features from our testing set test.csv
test_X = pd.get_dummies(test_X)

Enter features to be considered separated by a comma: 'Fence', 'MiscFeature', 'MiscVal', 'MoSold', 'YrSold', 'SaleType',        'SaleCondition'
['Fence', 'MiscFeature', 'MiscVal', 'MoSold', 'YrSold', 'SaleType', 'SaleCondition']

In [9]:
pos = 0
for col in train_X.columns:
    if not col in test_X.columns:
        test_X.insert(pos, col, 0)
    pos = pos + 1

In [10]:
train_X.columns

Index(['MiscVal', 'MoSold', 'YrSold', 'Fence_GdPrv', 'Fence_GdWo',
       'Fence_MnPrv', 'Fence_MnWw', 'MiscFeature_Gar2', 'MiscFeature_Othr',
       'MiscFeature_Shed', 'MiscFeature_TenC', 'SaleType_COD', 'SaleType_CWD',
       'SaleType_Con', 'SaleType_ConLD', 'SaleType_ConLI', 'SaleType_ConLw',
       'SaleType_New', 'SaleType_Oth', 'SaleType_WD', 'SaleCondition_Abnorml',
       'SaleCondition_AdjLand', 'SaleCondition_Alloca', 'SaleCondition_Family',
       'SaleCondition_Normal', 'SaleCondition_Partial'],
      dtype='object')

In [11]:
test_X.columns

Index(['MiscVal', 'MoSold', 'YrSold', 'Fence_GdPrv', 'Fence_GdWo',
       'Fence_MnPrv', 'Fence_MnWw', 'MiscFeature_Gar2', 'MiscFeature_Othr',
       'MiscFeature_Shed', 'MiscFeature_TenC', 'SaleType_COD', 'SaleType_CWD',
       'SaleType_Con', 'SaleType_ConLD', 'SaleType_ConLI', 'SaleType_ConLw',
       'SaleType_New', 'SaleType_Oth', 'SaleType_WD', 'SaleCondition_Abnorml',
       'SaleCondition_AdjLand', 'SaleCondition_Alloca', 'SaleCondition_Family',
       'SaleCondition_Normal', 'SaleCondition_Partial'],
      dtype='object')

In [12]:
home_model = DecisionTreeRegressor(random_state=1)
home_model.fit(train_X, train_y)


print("Making predictions for the following houses:")
test_X

Making predictions for the following houses:

,MiscVal,MoSold,YrSold,Fence_GdPrv,Fence_GdWo,Fence_MnPrv,Fence_MnWw,MiscFeature_Gar2,MiscFeature_Othr,MiscFeature_Shed,...,SaleType_ConLw,SaleType_New,SaleType_Oth,SaleType_WD,SaleCondition_Abnorml,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family,SaleCondition_Normal,SaleCondition_Partial
0,0,6,2010,0,0,1,0,0,0,0,...,0,0,0,1,0,0,0,0,1,0
1,12500,6,2010,0,0,0,0,1,0,0,...,0,0,0,1,0,0,0,0,1,0
2,0,3,2010,0,0,1,0,0,0,0,...,0,0,0,1,0,0,0,0,1,0
3,0,6,2010,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,1,0
4,0,1,2010,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1454,0,6,2006,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,1,0
1455,0,4,2006,0,0,0,0,0,0,0,...,0,0,0,1,1,0,0,0,0,0
1456,0,9,2006,0,0,0,0,0,0,0,...,0,0,0,1,1,0,0,0,0,0
1457,700,7,2006,0,0,1,0,0,0,1,...,0,0,0,1,0,0,0,0,1,0
1458,0,11,2006,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,1,0

In [13]:
print("The predictions are")
home_predictions = home_model.predict(test_X)
home_predictions

The predictions are

array([151333.33333333, 151500.        , 158000.        , ...,
       257000.        ,  88000.        , 241943.75      ])

In [20]:
ind = 1461
df = pd.DataFrame(columns=['Id','SalePrice'])
for price in home_predictions:
    newrow = pd.DataFrame({'Id': [ind], 'SalePrice':[price]})
    df = pd.concat([df, newrow], ignore_index = True)
    ind = ind + 1
    
df

        Id      SalePrice
0     1461  151333.333333
1     1462       151500.0
2     1463       158000.0
3     1464  176608.695652
4     1465       210075.0
...    ...            ...
1454  2915       170690.0
1455  2916  114050.666667
1456  2917       257000.0
1457  2918        88000.0
1458  2919      241943.75

[1459 rows x 2 columns]

In [21]:
df.to_csv (r'house_prices.csv', index=False, header=True)